% -*- octave -*-
% Johannes Willkomm 2008
% 

function res=plotResRatiosBar(versions, runName, timeCol, titelText)
  colNames = {"threads", ...
              "efficiency-time", "speedup-time", "time", ... 
              "efficiency-time-steps", "speedup-time-steps", "time-steps", ...
              "efficiency-steps", "speedup-steps", "steps", ...
              "memory", "rels", "dtests", ...
              "efficiency-update-index", "speedup-update-index", "update-index", ...
              "efficiency-summation", "speedup-summation", "summation", ...
              "efficiency-eval-state", "speedup-eval-state", "eval-state", ...
              "efficiency-update-state", "speedup-update-state", "update-state", ...
              "clear-scratch", "reduce-scratch"};

  tripels = { ...
             {"gcc", "intel64"} ; ...
             {"gcc", "amd64"} ; ...
             {"gcc", "ultraT2"} ; ...
             };

  threadsUltra = getCol2(versions, runName, "ultraT2", "gcc", ...
                        6, "naive", 1);

  numTests = size(threadsUltra,1);

  alldata = zeros(numTests, 4);
  legends = cell(6, 1);
  for i=1:size(tripels,1)
    trip=tripels{i,:};
    threadsNaive = getCol2(versions, runName, trip{2}, trip{1}, ...
                          6, "naive", 1);
    alldata(1:length(threadsNaive), 1) = threadsNaive;
    timesNaive6 = getCol2(versions, runName, trip{2}, trip{1}, ...
                         6, "naive", timeCol);
    timesNaive7 = getCol2(versions, runName, trip{2}, trip{1}, ...
                         7, "naive", timeCol);
    timesSym6 = getCol2(versions, runName, trip{2}, trip{1}, ...
                       6, "sym-naive", timeCol);
    timesSym7 = getCol2(versions, runName, trip{2}, trip{1}, ...
                       7, "sym-naive", timeCol);
                                %  semilogx(threadsNaive, timesNaive6 ./ timesSym6, ...
                                %           sprintf("rx-;%s, %s, naive(m=6) over sym(m=6);", trip{2}, trip{1}));
                                %  semilogx(threadsNaive, timesNaive7 ./ timesSym7, "g+-;naive, m=7 over sym, m=7;");
                                %  semilogx(threadsNaive, timesNaive7 ./ timesSym6, ...
                                %           sprintf("bo-;%s, %s, naive(m=7) over sym(m=6);", trip{2}, trip{1}));
    alldata(1:length(timesNaive7), 2*(i-1)+2) = timesNaive6 ./ timesSym6;
    legends{2*(i-1)+1} = ...
        sprintf("%s, %s, naive(M=64) over sym(M=64)", trip{2}, trip{1});
    alldata(1:length(timesNaive7), 2*(i-1)+3) = timesNaive7 ./ timesSym6;
    legends{2*(i-1)+2} = ...
        sprintf("%s, %s, naive(M=128) over sym(M=64)", trip{2}, trip{1});
  end
  res=figure;
  hold on;
%  title(["algorithm speedup, " colNames{timeCol}]);
  title(titelText);
  h1=bar(1:numTests, alldata(:,2:7), ...
         sprintf("bo-;%s, %s, naive(m=7) over sym(m=6);", trip{2}, trip{1}), 0.8, "grouped");
  legends
  legend(legends);
  set(gca, "ylim", [0, 5])
  set(gca, "key", "on")
  set(gca, "xtick", 1:numTests);
  labels = cell(numTests, 1);
  for i=1:numTests
    labels{i} = sprintf("%d", alldata(i,1));
  end
  set(gca, "xticklabel", labels)
  set(h1(1), "facecolor", "red")
  set(h1(2), "facecolor", [0.75, 0, 0])
  set(h1(3), "facecolor", "green")
  set(h1(4), "facecolor", [0, 0.75, 0])
  set(h1(5), "facecolor", "blue")
  set(h1(6), "facecolor", [0, 0, 0.75])
  ylabel('Ratio of naive/symmetric runtimes');
  xlabel('Threads');
